# Tab list player name format
# Supported variables are %name%, %displayname%, and %ping%
format: '%name% &7[&a%ping%ms&7]'
format-afk: '%name% &7[&a%ping%ms&7] &eAFK'

# Enable TPS/MSPT/Load/World display
# Supported variables are %tps%, %mspt%, %load%, and %world%
# Spigot only supports %world%
enable-tps: false
format-header: ''
format-footer: '&7TPS: %tps%   &7MSPT: %mspt%'

# Enable metrics (subject to bStats global config)
enable-metrics: true
