name: TabListPing
main: com.bobcat00.tablistping.TabListPing
version: '${project.version}'
author: Bobcat00
api-version: '1.18'
softdepend: [Essentials]
commands:
  tablistping:
    description: TabListPing commands
    aliases: tlp
    permission: tablistping.command
permissions:
  tablistping.header:
    description: Displays tab list header for this player
    default: false
  tablistping.footer:
    description: Displays tab list footer for this player
    default: false
  tablistping.command:
    description: Required permission for all subcommands
    default: op
    children:
      tablistping.command.reload: true
      tablistping.command.report: true
  tablistping.command.reload:
    description: Reload TabListPing config file
    default: op
  tablistping.command.report:
    description: Produce ping report
    default: op
