name: TabListPing
main: com.bobcat00.tablistping.TabListPing
version: '${project.version}'
author: Bobcat00
api-version: '1.18'
softdepend: [Essentials]
commands:
  tablistping:
    description: Reload TabListPing config file
    aliases: tlp
    usage: "Usage: /tablistping reload"
    permission: tablistping.reload
    permission-message: You do not have permission for this command
permissions:
  tablistping.header:
    description: Displays tab list header for this player
    default: false
  tablistping.footer:
    description: Displays tab list footer for this player
    default: false
  tablistping.reload:
    description: Reload TabListPing config file
    default: op
    