name: TabListPing
main: com.bobcat00.tablistping.TabListPing
version: ${project.version}
author: Bobcat00
api-version: 1.19
depend: [ProtocolLib]
softdepend: [Essentials]
permissions:
  tablistping.header:
    description: Displays tab list header for this player
    default: false
  tablistping.footer:
    description: Displays tab list footer for this player
    default: false
