name: TabListPing
main: com.bobcat00.tablistping.TabListPing
version: ${project.version}
author: Bobcat00
api-version: 1.19
depend: [ProtocolLib]
softdepend: [Essentials]
libraries:
    - net.kyori:adventure-api:4.12.0
    - net.kyori:adventure-text-minimessage:4.12.0
    - net.kyori:adventure-text-serializer-legacy:4.12.0
commands:
  tablistping:
    description: Reload TabListPing config file
    aliases: tlp
    usage: "Usage: /tablistping reload"
    permission: tablistping.reload
    permission-message: You do not have permission for this command
permissions:
  tablistping.header:
    description: Displays tab list header for this player
    default: false
  tablistping.footer:
    description: Displays tab list footer for this player
    default: false
  tablistping.reload:
    description: Reload TabListPing config file
    default: op
    